#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Afghouse_Loam01_door4m_wooddoor1

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass afghouse_Loam01_door4m_wooddoor1.afghouse_Loam01_door4m_wooddoor1_C
// 0x0020 (0x0258 - 0x0238)
class AAfghouse_Loam01_door4m_wooddoor1_C final : public AStaticMeshActor
{
public:
	class UStaticMeshComponent*                   Door_wood_2;                                       // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Plank_10x100x10;                                   // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Plank_10x200x101;                                  // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Plank_10x200x10;                                   // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"afghouse_Loam01_door4m_wooddoor1_C">();
	}
	static class AAfghouse_Loam01_door4m_wooddoor1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAfghouse_Loam01_door4m_wooddoor1_C>();
	}
};
static_assert(alignof(AAfghouse_Loam01_door4m_wooddoor1_C) == 0x000008, "Wrong alignment on AAfghouse_Loam01_door4m_wooddoor1_C");
static_assert(sizeof(AAfghouse_Loam01_door4m_wooddoor1_C) == 0x000258, "Wrong size on AAfghouse_Loam01_door4m_wooddoor1_C");
static_assert(offsetof(AAfghouse_Loam01_door4m_wooddoor1_C, Door_wood_2) == 0x000238, "Member 'AAfghouse_Loam01_door4m_wooddoor1_C::Door_wood_2' has a wrong offset!");
static_assert(offsetof(AAfghouse_Loam01_door4m_wooddoor1_C, Plank_10x100x10) == 0x000240, "Member 'AAfghouse_Loam01_door4m_wooddoor1_C::Plank_10x100x10' has a wrong offset!");
static_assert(offsetof(AAfghouse_Loam01_door4m_wooddoor1_C, Plank_10x200x101) == 0x000248, "Member 'AAfghouse_Loam01_door4m_wooddoor1_C::Plank_10x200x101' has a wrong offset!");
static_assert(offsetof(AAfghouse_Loam01_door4m_wooddoor1_C, Plank_10x200x10) == 0x000250, "Member 'AAfghouse_Loam01_door4m_wooddoor1_C::Plank_10x200x10' has a wrong offset!");

}

