#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AMMO_INS_Top

#include "Basic.hpp"


namespace SDK::Params
{

// Function AMMO_INS_Top.AMMO_INS_Top_C.ExecuteUbergraph_AMMO_INS_Top
// 0x0008 (0x0008 - 0x0000)
struct AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top) == 0x000004, "Wrong alignment on AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top");
static_assert(sizeof(AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top) == 0x000008, "Wrong size on AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top");
static_assert(offsetof(AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top, EntryPoint) == 0x000000, "Member 'AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top::EntryPoint' has a wrong offset!");
static_assert(offsetof(AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top, CallFunc_RandomFloatInRange_ReturnValue) == 0x000004, "Member 'AMMO_INS_Top_C_ExecuteUbergraph_AMMO_INS_Top::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");

}

