#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BMP1_Burn

#include "Basic.hpp"

#include "BP_GenericDestroyedVehicleWreck_Turreted_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BMP1_Burn.BMP1_Burn_C
// 0x0010 (0x03E8 - 0x03D8)
class ABMP1_Burn_C : public ABP_GenericDestroyedVehicleWreck_Turreted_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USQArmorMeshComponent*                  SQArmorMesh;                                       // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BMP1_Burn(int32 EntryPoint);
	void BndEvt__BMP1_Burn_SQVehicleWreckTurret_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BMP1_Burn_C">();
	}
	static class ABMP1_Burn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABMP1_Burn_C>();
	}
};
static_assert(alignof(ABMP1_Burn_C) == 0x000008, "Wrong alignment on ABMP1_Burn_C");
static_assert(sizeof(ABMP1_Burn_C) == 0x0003E8, "Wrong size on ABMP1_Burn_C");
static_assert(offsetof(ABMP1_Burn_C, UberGraphFrame) == 0x0003D8, "Member 'ABMP1_Burn_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABMP1_Burn_C, SQArmorMesh) == 0x0003E0, "Member 'ABMP1_Burn_C::SQArmorMesh' has a wrong offset!");

}

