#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_2A20_HEAT

#include "Basic.hpp"

#include "BP_2A20_AP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_2A20_HEAT.BP_2A20_HEAT_C
// 0x0000 (0x0C60 - 0x0C60)
class ABP_2A20_HEAT_C final : public ABP_2A20_AP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_2A20_HEAT_C">();
	}
	static class ABP_2A20_HEAT_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_2A20_HEAT_C>();
	}
};
static_assert(alignof(ABP_2A20_HEAT_C) == 0x000010, "Wrong alignment on ABP_2A20_HEAT_C");
static_assert(sizeof(ABP_2A20_HEAT_C) == 0x000C60, "Wrong size on ABP_2A20_HEAT_C");

}

