#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EquippableRallyPoint_BAF

#include "Basic.hpp"

#include "BP_EquippableRallyPoint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EquippableRallyPoint_BAF.BP_EquippableRallyPoint_BAF_C
// 0x0000 (0x04D0 - 0x04D0)
class ABP_EquippableRallyPoint_BAF_C final : public ABP_EquippableRallyPoint_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EquippableRallyPoint_BAF_C">();
	}
	static class ABP_EquippableRallyPoint_BAF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EquippableRallyPoint_BAF_C>();
	}
};
static_assert(alignof(ABP_EquippableRallyPoint_BAF_C) == 0x000008, "Wrong alignment on ABP_EquippableRallyPoint_BAF_C");
static_assert(sizeof(ABP_EquippableRallyPoint_BAF_C) == 0x0004D0, "Wrong size on ABP_EquippableRallyPoint_BAF_C");

}

