#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EmplacedSPG9_Tripod

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_EmplacedSPG9_Tripod.BP_EmplacedSPG9_Tripod_C.GetSoldierAttachComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent final
{
public:
	class USceneComponent*                        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent) == 0x000008, "Wrong alignment on BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent");
static_assert(sizeof(BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent) == 0x000008, "Wrong size on BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent");
static_assert(offsetof(BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent, ReturnValue) == 0x000000, "Member 'BP_EmplacedSPG9_Tripod_C_GetSoldierAttachComponent::ReturnValue' has a wrong offset!");

}

