#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_L16mortar_Deployable

#include "Basic.hpp"

#include "BP_m252mortar_Deployable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_L16mortar_Deployable.BP_L16mortar_Deployable_C
// 0x0000 (0x05E8 - 0x05E8)
class ABP_L16mortar_Deployable_C final : public ABP_m252mortar_Deployable_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_L16mortar_Deployable_C">();
	}
	static class ABP_L16mortar_Deployable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_L16mortar_Deployable_C>();
	}
};
static_assert(alignof(ABP_L16mortar_Deployable_C) == 0x000008, "Wrong alignment on ABP_L16mortar_Deployable_C");
static_assert(sizeof(ABP_L16mortar_Deployable_C) == 0x0005E8, "Wrong size on ABP_L16mortar_Deployable_C");

}

