#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_L85A2_ACOG

#include "Basic.hpp"

#include "BP_L85A2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_L85A2_ACOG.BP_L85A2_ACOG_C
// 0x0010 (0x09B0 - 0x09A0)
class ABP_L85A2_ACOG_C final : public ABP_L85A2_C
{
public:
	class UBP_Pip_C*                              BP_Pip;                                            // 0x09A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LensMesh;                                          // 0x09A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_L85A2_ACOG_C">();
	}
	static class ABP_L85A2_ACOG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_L85A2_ACOG_C>();
	}
};
static_assert(alignof(ABP_L85A2_ACOG_C) == 0x000010, "Wrong alignment on ABP_L85A2_ACOG_C");
static_assert(sizeof(ABP_L85A2_ACOG_C) == 0x0009B0, "Wrong size on ABP_L85A2_ACOG_C");
static_assert(offsetof(ABP_L85A2_ACOG_C, BP_Pip) == 0x0009A0, "Member 'ABP_L85A2_ACOG_C::BP_Pip' has a wrong offset!");
static_assert(offsetof(ABP_L85A2_ACOG_C, LensMesh) == 0x0009A8, "Member 'ABP_L85A2_ACOG_C::LensMesh' has a wrong offset!");

}

