#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerSoundStateButton

#include "Basic.hpp"

#include "BP_PlayerSoundStateButton_classes.hpp"
#include "BP_PlayerSoundStateButton_parameters.hpp"


namespace SDK
{

// Function BP_PlayerSoundStateButton.BP_PlayerSoundStateButton_C.ExecuteUbergraph_BP_PlayerSoundStateButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PlayerSoundStateButton_C::ExecuteUbergraph_BP_PlayerSoundStateButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerSoundStateButton_C", "ExecuteUbergraph_BP_PlayerSoundStateButton");

	Params::BP_PlayerSoundStateButton_C_ExecuteUbergraph_BP_PlayerSoundStateButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerSoundStateButton.BP_PlayerSoundStateButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PlayerSoundStateButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerSoundStateButton_C", "PreConstruct");

	Params::BP_PlayerSoundStateButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

