#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Soviet_Binoculars

#include "Basic.hpp"

#include "BP_GenericBinoculars_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Soviet_Binoculars.BP_Soviet_Binoculars_C
// 0x0000 (0x09B0 - 0x09B0)
class ABP_Soviet_Binoculars_C final : public ABP_GenericBinoculars_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Soviet_Binoculars_C">();
	}
	static class ABP_Soviet_Binoculars_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Soviet_Binoculars_C>();
	}
};
static_assert(alignof(ABP_Soviet_Binoculars_C) == 0x000010, "Wrong alignment on ABP_Soviet_Binoculars_C");
static_assert(sizeof(ABP_Soviet_Binoculars_C) == 0x0009B0, "Wrong size on ABP_Soviet_Binoculars_C");

}

