#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SQRestriction_RoleCount

#include "Basic.hpp"

#include "SQRoleTags_structs.hpp"


namespace SDK::Params
{

// Function BP_SQRestriction_RoleCount.BP_SQRestriction_RoleCount_C.ShouldBeCounted
// 0x0058 (0x0058 - 0x0000)
struct BP_SQRestriction_RoleCount_C_ShouldBeCounted final
{
public:
	class USQRoleSettings*                        In_Tested_Role_Setting;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        In_Searched_Role_Setting_If_No_Tags;               // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Out_Should_Be_Counted;                             // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BC7[0x6];                                     // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ESQRoleTags>                           CallFunc_Set_ToArray_Result;                       // 0x0018(0x0010)(ReferenceParm)
	class UBP_SQRoleSettings_C*                   K2Node_DynamicCast_AsBP_SQRole_Settings;           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasTags_Out_Has_Tags;                     // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BC8[0x1];                                     // 0x0033(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Set_Length_ReturnValue;                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BC9[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ESQRoleTags>                           CallFunc_Set_ToArray_Result_1;                     // 0x0040(0x0010)(ReferenceParm)
	int32                                         CallFunc_Set_Length_ReturnValue_1;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasTags_Out_Has_Tags_1;                   // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SQRestriction_RoleCount_C_ShouldBeCounted) == 0x000008, "Wrong alignment on BP_SQRestriction_RoleCount_C_ShouldBeCounted");
static_assert(sizeof(BP_SQRestriction_RoleCount_C_ShouldBeCounted) == 0x000058, "Wrong size on BP_SQRestriction_RoleCount_C_ShouldBeCounted");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, In_Tested_Role_Setting) == 0x000000, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::In_Tested_Role_Setting' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, In_Searched_Role_Setting_If_No_Tags) == 0x000008, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::In_Searched_Role_Setting_If_No_Tags' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, Out_Should_Be_Counted) == 0x000010, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::Out_Should_Be_Counted' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000011, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Set_ToArray_Result) == 0x000018, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Set_ToArray_Result' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, K2Node_DynamicCast_AsBP_SQRole_Settings) == 0x000028, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::K2Node_DynamicCast_AsBP_SQRole_Settings' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_HasTags_Out_Has_Tags) == 0x000031, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_HasTags_Out_Has_Tags' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Not_PreBool_ReturnValue) == 0x000032, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Set_Length_ReturnValue) == 0x000034, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Set_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Greater_IntInt_ReturnValue) == 0x000038, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Set_ToArray_Result_1) == 0x000040, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Set_ToArray_Result_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Set_Length_ReturnValue_1) == 0x000050, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Set_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_HasTags_Out_Has_Tags_1) == 0x000054, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_HasTags_Out_Has_Tags_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldBeCounted, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000055, "Member 'BP_SQRestriction_RoleCount_C_ShouldBeCounted::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");

// Function BP_SQRestriction_RoleCount.BP_SQRestriction_RoleCount_C.GetTeamUsage
// 0x0048 (0x0048 - 0x0000)
struct BP_SQRestriction_RoleCount_C_GetTeamUsage final
{
public:
	class ASQTeam*                                In_Team;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        In_Setting;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Out_Usage;                                         // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         L_Used;                                            // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BCA[0x3];                                     // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BCB[0x2];                                     // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BCC[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASQPlayerState*                         CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ShouldPlayerBeCounted_Out_Should_Count;   // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BCD[0x2];                                     // 0x0042(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SQRestriction_RoleCount_C_GetTeamUsage) == 0x000008, "Wrong alignment on BP_SQRestriction_RoleCount_C_GetTeamUsage");
static_assert(sizeof(BP_SQRestriction_RoleCount_C_GetTeamUsage) == 0x000048, "Wrong size on BP_SQRestriction_RoleCount_C_GetTeamUsage");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, In_Team) == 0x000000, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::In_Team' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, In_Setting) == 0x000008, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::In_Setting' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, Out_Usage) == 0x000010, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::Out_Usage' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, L_Used) == 0x000014, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::L_Used' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, Temp_int_Loop_Counter_Variable) == 0x000018, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_Array_Length_ReturnValue) == 0x000024, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_IsValid_ReturnValue_1) == 0x000028, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_Less_IntInt_ReturnValue) == 0x000029, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, Temp_int_Array_Index_Variable) == 0x00002C, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, Temp_int_Variable) == 0x000030, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_Array_Get_Item) == 0x000038, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_IsValid_ReturnValue_2) == 0x000040, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_ShouldPlayerBeCounted_Out_Should_Count) == 0x000041, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_ShouldPlayerBeCounted_Out_Should_Count' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetTeamUsage, CallFunc_Add_IntInt_ReturnValue_1) == 0x000044, "Member 'BP_SQRestriction_RoleCount_C_GetTeamUsage::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");

// Function BP_SQRestriction_RoleCount.BP_SQRestriction_RoleCount_C.GetSquadUsage
// 0x0048 (0x0048 - 0x0000)
struct BP_SQRestriction_RoleCount_C_GetSquadUsage final
{
public:
	class ASQPlayerController*                    In_Player;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        In_Setting;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Out_Usage;                                         // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         L_Used;                                            // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BCE[0x2];                                     // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BCF[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASQPlayerState*                         CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldPlayerBeCounted_Out_Should_Count;   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BD0[0x2];                                     // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BD1[0x3];                                     // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SQRestriction_RoleCount_C_GetSquadUsage) == 0x000008, "Wrong alignment on BP_SQRestriction_RoleCount_C_GetSquadUsage");
static_assert(sizeof(BP_SQRestriction_RoleCount_C_GetSquadUsage) == 0x000048, "Wrong size on BP_SQRestriction_RoleCount_C_GetSquadUsage");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, In_Player) == 0x000000, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::In_Player' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, In_Setting) == 0x000008, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::In_Setting' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, Out_Usage) == 0x000010, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::Out_Usage' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, L_Used) == 0x000014, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::L_Used' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_IsValid_ReturnValue_1) == 0x000019, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_Array_Get_Item) == 0x000028, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_ShouldPlayerBeCounted_Out_Should_Count) == 0x000030, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_ShouldPlayerBeCounted_Out_Should_Count' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_IsValid_ReturnValue_2) == 0x000031, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, Temp_int_Loop_Counter_Variable) == 0x000034, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_Add_IntInt_ReturnValue) == 0x00003C, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, Temp_int_Variable) == 0x000040, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_GetSquadUsage, CallFunc_Add_IntInt_ReturnValue_1) == 0x000044, "Member 'BP_SQRestriction_RoleCount_C_GetSquadUsage::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");

// Function BP_SQRestriction_RoleCount.BP_SQRestriction_RoleCount_C.ShouldPlayerBeCounted
// 0x0030 (0x0030 - 0x0000)
struct BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted final
{
public:
	class ASQPlayerState*                         In_Player;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        In_Searched_Role_Setting_If_No_Tags;               // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Out_Should_Count;                                  // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CachedShouldBeCountedCurRole;                      // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BD2[0x6];                                     // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USQRoleSettings*                        CallFunc_GetDeployRole_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQRoleSettings*                        CallFunc_GetCurrentRole_ReturnValue;               // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ShouldBeCounted_Out_Should_Be_Counted;    // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ShouldBeCounted_Out_Should_Be_Counted_1;  // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted) == 0x000008, "Wrong alignment on BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted");
static_assert(sizeof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted) == 0x000030, "Wrong size on BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, In_Player) == 0x000000, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::In_Player' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, In_Searched_Role_Setting_If_No_Tags) == 0x000008, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::In_Searched_Role_Setting_If_No_Tags' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, Out_Should_Count) == 0x000010, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::Out_Should_Count' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CachedShouldBeCountedCurRole) == 0x000011, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CachedShouldBeCountedCurRole' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_GetDeployRole_ReturnValue) == 0x000018, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_GetDeployRole_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_GetCurrentRole_ReturnValue) == 0x000020, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_GetCurrentRole_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_IsValid_ReturnValue_1) == 0x000029, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_ShouldBeCounted_Out_Should_Be_Counted) == 0x00002A, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_ShouldBeCounted_Out_Should_Be_Counted' has a wrong offset!");
static_assert(offsetof(BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted, CallFunc_ShouldBeCounted_Out_Should_Be_Counted_1) == 0x00002B, "Member 'BP_SQRestriction_RoleCount_C_ShouldPlayerBeCounted::CallFunc_ShouldBeCounted_Out_Should_Be_Counted_1' has a wrong offset!");

}

