#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SQToastWidget

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SQToastWidget.BP_SQToastWidget_C.ExecuteUbergraph_BP_SQToastWidget
// 0x0020 (0x0020 - 0x0000)
struct BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_306A[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_ToastText;                      // 0x0008(0x0018)()
};
static_assert(alignof(BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget) == 0x000008, "Wrong alignment on BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget");
static_assert(sizeof(BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget) == 0x000020, "Wrong size on BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget");
static_assert(offsetof(BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget, EntryPoint) == 0x000000, "Member 'BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget, K2Node_CustomEvent_ToastText) == 0x000008, "Member 'BP_SQToastWidget_C_ExecuteUbergraph_BP_SQToastWidget::K2Node_CustomEvent_ToastText' has a wrong offset!");

// Function BP_SQToastWidget.BP_SQToastWidget_C.ToastTextUpdated_Event
// 0x0018 (0x0018 - 0x0000)
struct BP_SQToastWidget_C_ToastTextUpdated_Event final
{
public:
	class FText                                   Param_ToastText;                                   // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_SQToastWidget_C_ToastTextUpdated_Event) == 0x000008, "Wrong alignment on BP_SQToastWidget_C_ToastTextUpdated_Event");
static_assert(sizeof(BP_SQToastWidget_C_ToastTextUpdated_Event) == 0x000018, "Wrong size on BP_SQToastWidget_C_ToastTextUpdated_Event");
static_assert(offsetof(BP_SQToastWidget_C_ToastTextUpdated_Event, Param_ToastText) == 0x000000, "Member 'BP_SQToastWidget_C_ToastTextUpdated_Event::Param_ToastText' has a wrong offset!");

}

