#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerPassword

#include "Basic.hpp"

#include "BP_ServerPassword_classes.hpp"
#include "BP_ServerPassword_parameters.hpp"


namespace SDK
{

// Function BP_ServerPassword.BP_ServerPassword_C.Password Entered__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Password                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UBP_ServerPassword_C*             Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerPassword_C::Password_Entered__DelegateSignature(const class FString& Password, class UBP_ServerPassword_C* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "Password Entered__DelegateSignature");

	Params::BP_ServerPassword_C_Password_Entered__DelegateSignature Parms{};

	Parms.Password = std::move(Password);
	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ServerPassword.BP_ServerPassword_C.Password Cancelled__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UBP_ServerPassword_C::Password_Cancelled__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "Password Cancelled__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ServerPassword.BP_ServerPassword_C.ExecuteUbergraph_BP_ServerPassword
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerPassword_C::ExecuteUbergraph_BP_ServerPassword(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "ExecuteUbergraph_BP_ServerPassword");

	Params::BP_ServerPassword_C_ExecuteUbergraph_BP_ServerPassword Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ServerPassword.BP_ServerPassword_C.BndEvt__BP_ServerPassword_AcceptButton_1_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UW_MainMenuButton_C*              Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerPassword_C::BndEvt__BP_ServerPassword_AcceptButton_1_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(bool bSelected, class UW_MainMenuButton_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "BndEvt__BP_ServerPassword_AcceptButton_1_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	Params::BP_ServerPassword_C_BndEvt__BP_ServerPassword_AcceptButton_1_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ServerPassword.BP_ServerPassword_C.BndEvt__EditableText_0_K2Node_ComponentBoundEvent_1_OnEditableTextCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerPassword_C::BndEvt__EditableText_0_K2Node_ComponentBoundEvent_1_OnEditableTextCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "BndEvt__EditableText_0_K2Node_ComponentBoundEvent_1_OnEditableTextCommittedEvent__DelegateSignature");

	Params::BP_ServerPassword_C_BndEvt__EditableText_0_K2Node_ComponentBoundEvent_1_OnEditableTextCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ServerPassword.BP_ServerPassword_C.BndEvt__DenyButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMainMenu_Button_C*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ServerPassword_C::BndEvt__DenyButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ServerPassword_C", "BndEvt__DenyButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	Params::BP_ServerPassword_C_BndEvt__DenyButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}

}

