#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TankNameManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TankNameManager.BP_TankNameManager_C
// 0x0030 (0x0258 - 0x0228)
class ABP_TankNameManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<uint8>                                 RandomizeArrayOfNameIDs;                           // 0x0238(0x0010)(Edit, BlueprintVisible)
	TArray<class UBP_TurretTankNameGenerator_C*>  Assigned_Tanks;                                    // 0x0248(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)

public:
	void ExecuteUbergraph_BP_TankNameManager(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Populate_And_Randomize_List();
	void Query_Name(const class UBP_TurretTankNameGenerator_C*& ItemToFind, uint8* Output);
	void Register_Turret(const class UBP_TurretTankNameGenerator_C*& Component);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TankNameManager_C">();
	}
	static class ABP_TankNameManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TankNameManager_C>();
	}
};
static_assert(alignof(ABP_TankNameManager_C) == 0x000008, "Wrong alignment on ABP_TankNameManager_C");
static_assert(sizeof(ABP_TankNameManager_C) == 0x000258, "Wrong size on ABP_TankNameManager_C");
static_assert(offsetof(ABP_TankNameManager_C, UberGraphFrame) == 0x000228, "Member 'ABP_TankNameManager_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_TankNameManager_C, DefaultSceneRoot) == 0x000230, "Member 'ABP_TankNameManager_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_TankNameManager_C, RandomizeArrayOfNameIDs) == 0x000238, "Member 'ABP_TankNameManager_C::RandomizeArrayOfNameIDs' has a wrong offset!");
static_assert(offsetof(ABP_TankNameManager_C, Assigned_Tanks) == 0x000248, "Member 'ABP_TankNameManager_C::Assigned_Tanks' has a wrong offset!");

}

