#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPRadialPopulatorChangeRole

#include "Basic.hpp"

#include "BPRadialPopulatorChangeRole_classes.hpp"
#include "BPRadialPopulatorChangeRole_parameters.hpp"


namespace SDK
{

// Function BPRadialPopulatorChangeRole.BPRadialPopulatorChangeRole_C.ExecuteUbergraph_BPRadialPopulatorChangeRole
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPRadialPopulatorChangeRole_C::ExecuteUbergraph_BPRadialPopulatorChangeRole(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPRadialPopulatorChangeRole_C", "ExecuteUbergraph_BPRadialPopulatorChangeRole");

	Params::BPRadialPopulatorChangeRole_C_ExecuteUbergraph_BPRadialPopulatorChangeRole Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPRadialPopulatorChangeRole.BPRadialPopulatorChangeRole_C.InitialSetup
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USQUserWidget*                    Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBP_RadialItemModel_C*            Model                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBaseRadialMenu_C*                RadialMenu                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPRadialPopulatorChangeRole_C::InitialSetup(class USQUserWidget* Widget, class UBP_RadialItemModel_C* Model, class UBaseRadialMenu_C* RadialMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPRadialPopulatorChangeRole_C", "InitialSetup");

	Params::BPRadialPopulatorChangeRole_C_InitialSetup Parms{};

	Parms.Widget = Widget;
	Parms.Model = Model;
	Parms.RadialMenu = RadialMenu;

	UObject::ProcessEvent(Func, &Parms);
}

}

