#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BritUtilTruck_Obliterate

#include "Basic.hpp"

#include "US_Util_Obliterate_desert_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BritUtilTruck_Obliterate.BritUtilTruck_Obliterate_C
// 0x0000 (0x03C8 - 0x03C8)
class ABritUtilTruck_Obliterate_C : public AUS_Util_Obliterate_desert_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BritUtilTruck_Obliterate_C">();
	}
	static class ABritUtilTruck_Obliterate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABritUtilTruck_Obliterate_C>();
	}
};
static_assert(alignof(ABritUtilTruck_Obliterate_C) == 0x000008, "Wrong alignment on ABritUtilTruck_Obliterate_C");
static_assert(sizeof(ABritUtilTruck_Obliterate_C) == 0x0003C8, "Wrong size on ABritUtilTruck_Obliterate_C");

}

