#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerEnvironmentInteraction

#include "Basic.hpp"

#include "PlayerEnvironmentInteraction_classes.hpp"
#include "PlayerEnvironmentInteraction_parameters.hpp"


namespace SDK
{

// Function PlayerEnvironmentInteraction.PlayerEnvironmentInteraction_C.ExecuteUbergraph_PlayerEnvironmentInteraction
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayerEnvironmentInteraction_C::ExecuteUbergraph_PlayerEnvironmentInteraction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerEnvironmentInteraction_C", "ExecuteUbergraph_PlayerEnvironmentInteraction");

	Params::PlayerEnvironmentInteraction_C_ExecuteUbergraph_PlayerEnvironmentInteraction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerEnvironmentInteraction.PlayerEnvironmentInteraction_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UPlayerEnvironmentInteraction_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerEnvironmentInteraction_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerEnvironmentInteraction.PlayerEnvironmentInteraction_C.ApplyFrontProjection
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UPlayerEnvironmentInteraction_C::ApplyFrontProjection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerEnvironmentInteraction_C", "ApplyFrontProjection");

	Params::PlayerEnvironmentInteraction_C_ApplyFrontProjection Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerEnvironmentInteraction.PlayerEnvironmentInteraction_C.CanTrace
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UPlayerEnvironmentInteraction_C::CanTrace()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerEnvironmentInteraction_C", "CanTrace");

	Params::PlayerEnvironmentInteraction_C_CanTrace Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerEnvironmentInteraction.PlayerEnvironmentInteraction_C.ExcludePlayerPatch
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPlayerEnvironmentInteraction_C::ExcludePlayerPatch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerEnvironmentInteraction_C", "ExcludePlayerPatch");

	UObject::ProcessEvent(Func, nullptr);
}

}

