#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RadialCenterVehicle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Squad_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass RadialCenterVehicle.RadialCenterVehicle_C
// 0x0098 (0x03C8 - 0x0330)
class URadialCenterVehicle_C final : public USQRadialButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 bigbackground;                                     // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             EnterExitText;                                     // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Smallcirclebackground;                             // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SupplyTimer;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextCenter;                                        // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Entry_Supply;                       // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBaseRadialMenu_C*                      OwnerRadialMenu;                                   // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_RadialItemModel_C*                  RelatedActionModel;                                // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Hovered;                                           // 0x0388(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_369B[0x7];                                     // 0x0389(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Ammo_Text;                                         // 0x0390(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ASQVehicle*                             Vehicle;                                           // 0x03A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMG_SeatProgress_C*                    ParentProgressBar;                                 // 0x03B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UComp_ResourceControl_C*                Resource_Supply_Controller;                        // 0x03B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MI_Timer;                                          // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_RadialCenterVehicle(int32 EntryPoint);
	void Construct();
	void OnHoverEnd();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnHoverBegin();
	struct FLinearColor Get_Background_ColorAndOpacity_0();
	void SetTimerProgress(float RemainingTimePct);
	void SetTimerActivation(bool Active);
	class FText Get_Text_SupplyStatus();
	void Vehicle_Speed_Check(bool* Speed_Is_Valid);
	bool Vehicle_Denied();
	void Is_Action_Ammo(bool* Is_Ammo_Action);
	void Validate_Transaction(bool* Valid, bool* Con_Valid, bool* Ammo_Valid, bool* Is_Loading, bool* Zone_has_Points);
	void Validate_FOB(bool* Valid);
	class FText Get_Action_Text();
	void Get_Widget_Text(class USQRadialButton* Button, class FText* DisplayText);
	void Is_Soldier_Alive(bool* Alive);
	void HelicopterAltitudeCheck(bool* AltitudeValid);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RadialCenterVehicle_C">();
	}
	static class URadialCenterVehicle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URadialCenterVehicle_C>();
	}
};
static_assert(alignof(URadialCenterVehicle_C) == 0x000008, "Wrong alignment on URadialCenterVehicle_C");
static_assert(sizeof(URadialCenterVehicle_C) == 0x0003C8, "Wrong size on URadialCenterVehicle_C");
static_assert(offsetof(URadialCenterVehicle_C, UberGraphFrame) == 0x000330, "Member 'URadialCenterVehicle_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, bigbackground) == 0x000338, "Member 'URadialCenterVehicle_C::bigbackground' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, EnterExitText) == 0x000340, "Member 'URadialCenterVehicle_C::EnterExitText' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Icon) == 0x000348, "Member 'URadialCenterVehicle_C::Icon' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Image_2) == 0x000350, "Member 'URadialCenterVehicle_C::Image_2' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Smallcirclebackground) == 0x000358, "Member 'URadialCenterVehicle_C::Smallcirclebackground' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, SupplyTimer) == 0x000360, "Member 'URadialCenterVehicle_C::SupplyTimer' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, TextCenter) == 0x000368, "Member 'URadialCenterVehicle_C::TextCenter' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, WidgetSwitcher_Entry_Supply) == 0x000370, "Member 'URadialCenterVehicle_C::WidgetSwitcher_Entry_Supply' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, OwnerRadialMenu) == 0x000378, "Member 'URadialCenterVehicle_C::OwnerRadialMenu' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, RelatedActionModel) == 0x000380, "Member 'URadialCenterVehicle_C::RelatedActionModel' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Hovered) == 0x000388, "Member 'URadialCenterVehicle_C::Hovered' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Ammo_Text) == 0x000390, "Member 'URadialCenterVehicle_C::Ammo_Text' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Vehicle) == 0x0003A8, "Member 'URadialCenterVehicle_C::Vehicle' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, ParentProgressBar) == 0x0003B0, "Member 'URadialCenterVehicle_C::ParentProgressBar' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, Resource_Supply_Controller) == 0x0003B8, "Member 'URadialCenterVehicle_C::Resource_Supply_Controller' has a wrong offset!");
static_assert(offsetof(URadialCenterVehicle_C, MI_Timer) == 0x0003C0, "Member 'URadialCenterVehicle_C::MI_Timer' has a wrong offset!");

}

