#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Command_ActionControl

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_Command_ActionControl.W_Command_ActionControl_C.ExecuteUbergraph_W_Command_ActionControl
// 0x01D0 (0x01D0 - 0x0000)
struct W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B1[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_PlayerController_C> K2Node_DynamicCast_AsBPI_Player_Controller;        // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B2[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASQPlayerController*                    K2Node_DynamicCast_AsSQPlayer_Controller;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B3[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQCommanderInputComponent*             CallFunc_GetComponentByClass_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCommander_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B4[0x2];                                     // 0x0042(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Get_Angle_Widget_Angle;                   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Get_Angle_World_Rotation;                 // 0x0048(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Get_World_Distance_World_Distance;        // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B5[0x6];                                     // 0x005A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerEvent                          K2Node_Event_Mouse_Event;                          // 0x0060(0x0070)()
	struct FVector                                K2Node_Event_World_Location;                       // 0x00D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Validate_Action_Valid;                    // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B6[0x2];                                     // 0x00DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RebaseLocalOriginOntoZero_ReturnValue;    // 0x00E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B7[0xB];                                     // 0x00F5(0x000B)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0100(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0130(0x0030)(IsPlainOldData, NoDestructor)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBPI_HUD_C>            K2Node_DynamicCast_AsBPI_HUD;                      // 0x0168(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B8[0x6];                                     // 0x017A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_SQMapCore_C*                         CallFunc_Get_Map_Core_Map_Core;                    // 0x0180(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45B9[0x3];                                     // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_GetMapBoundsScale_ReturnValue;            // 0x018C(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RebaseLocalOriginOntoZero_ReturnValue_1;  // 0x0194(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBox2D                                 CallFunc_GetWorldBounds_ReturnValue;               // 0x01A0(0x0014)(ConstParm, ZeroConstructor, NoDestructor)
	struct FVector2D                              CallFunc_WorldToMapLocation_OutMapLocation;        // 0x01B4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_WorldToMapLocation_ReturnValue;           // 0x01BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45BA[0x3];                                     // 0x01BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue;             // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl) == 0x000010, "Wrong alignment on W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl");
static_assert(sizeof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl) == 0x0001D0, "Wrong size on W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, EntryPoint) == 0x000000, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, Temp_bool_Has_Been_Initd_Variable) == 0x000004, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_AsBPI_Player_Controller) == 0x000010, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_AsBPI_Player_Controller' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_AsSQPlayer_Controller) == 0x000028, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_AsSQPlayer_Controller' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_bSuccess_1) == 0x000030, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetComponentByClass_ReturnValue) == 0x000038, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsCommander_ReturnValue) == 0x000040, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsCommander_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue) == 0x000041, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_Get_Angle_Widget_Angle) == 0x000044, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_Get_Angle_Widget_Angle' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_Get_Angle_World_Rotation) == 0x000048, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_Get_Angle_World_Rotation' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_Get_World_Distance_World_Distance) == 0x000054, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_Get_World_Distance_World_Distance' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue_1) == 0x000058, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, Temp_bool_IsClosed_Variable) == 0x000059, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_Event_Mouse_Event) == 0x000060, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_Event_Mouse_Event' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_Event_World_Location) == 0x0000D0, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_Event_World_Location' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue_2) == 0x0000DC, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_Validate_Action_Valid) == 0x0000DD, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_Validate_Action_Valid' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x0000E0, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_RebaseLocalOriginOntoZero_ReturnValue) == 0x0000E8, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_RebaseLocalOriginOntoZero_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue_3) == 0x0000F4, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_MakeTransform_ReturnValue) == 0x000100, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_MakeTransform_ReturnValue_1) == 0x000130, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetHUD_ReturnValue) == 0x000160, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_AsBPI_HUD) == 0x000168, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_AsBPI_HUD' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, K2Node_DynamicCast_bSuccess_2) == 0x000178, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue_4) == 0x000179, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_Get_Map_Core_Map_Core) == 0x000180, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_Get_Map_Core_Map_Core' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_IsValid_ReturnValue_5) == 0x000188, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetMapBoundsScale_ReturnValue) == 0x00018C, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetMapBoundsScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_RebaseLocalOriginOntoZero_ReturnValue_1) == 0x000194, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_RebaseLocalOriginOntoZero_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_GetWorldBounds_ReturnValue) == 0x0001A0, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_GetWorldBounds_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_WorldToMapLocation_OutMapLocation) == 0x0001B4, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_WorldToMapLocation_OutMapLocation' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_WorldToMapLocation_ReturnValue) == 0x0001BC, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_WorldToMapLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl, CallFunc_AddChildToCanvas_ReturnValue) == 0x0001C0, "Member 'W_Command_ActionControl_C_ExecuteUbergraph_W_Command_ActionControl::CallFunc_AddChildToCanvas_ReturnValue' has a wrong offset!");

// Function W_Command_ActionControl.W_Command_ActionControl_C.On Map Mouse Down
// 0x0080 (0x0080 - 0x0000)
struct W_Command_ActionControl_C_On_Map_Mouse_Down final
{
public:
	struct FPointerEvent                          Mouse_Event;                                       // 0x0000(0x0070)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FVector                                World_Location;                                    // 0x0070(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Command_ActionControl_C_On_Map_Mouse_Down) == 0x000008, "Wrong alignment on W_Command_ActionControl_C_On_Map_Mouse_Down");
static_assert(sizeof(W_Command_ActionControl_C_On_Map_Mouse_Down) == 0x000080, "Wrong size on W_Command_ActionControl_C_On_Map_Mouse_Down");
static_assert(offsetof(W_Command_ActionControl_C_On_Map_Mouse_Down, Mouse_Event) == 0x000000, "Member 'W_Command_ActionControl_C_On_Map_Mouse_Down::Mouse_Event' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_On_Map_Mouse_Down, World_Location) == 0x000070, "Member 'W_Command_ActionControl_C_On_Map_Mouse_Down::World_Location' has a wrong offset!");

// Function W_Command_ActionControl.W_Command_ActionControl_C.Get Angle
// 0x0028 (0x0028 - 0x0000)
struct W_Command_ActionControl_C_Get_Angle final
{
public:
	float                                         Widget_Angle;                                      // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               World_Rotation;                                    // 0x0004(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPanelWidget*                           CallFunc_GetMapBody_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Get_Angle_From_Mouse_Vector_Angle;        // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Get_Angle_From_Mouse_Vector_World_Rotation; // 0x001C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Command_ActionControl_C_Get_Angle) == 0x000008, "Wrong alignment on W_Command_ActionControl_C_Get_Angle");
static_assert(sizeof(W_Command_ActionControl_C_Get_Angle) == 0x000028, "Wrong size on W_Command_ActionControl_C_Get_Angle");
static_assert(offsetof(W_Command_ActionControl_C_Get_Angle, Widget_Angle) == 0x000000, "Member 'W_Command_ActionControl_C_Get_Angle::Widget_Angle' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Angle, World_Rotation) == 0x000004, "Member 'W_Command_ActionControl_C_Get_Angle::World_Rotation' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Angle, CallFunc_GetMapBody_ReturnValue) == 0x000010, "Member 'W_Command_ActionControl_C_Get_Angle::CallFunc_GetMapBody_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Angle, CallFunc_Get_Angle_From_Mouse_Vector_Angle) == 0x000018, "Member 'W_Command_ActionControl_C_Get_Angle::CallFunc_Get_Angle_From_Mouse_Vector_Angle' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Angle, CallFunc_Get_Angle_From_Mouse_Vector_World_Rotation) == 0x00001C, "Member 'W_Command_ActionControl_C_Get_Angle::CallFunc_Get_Angle_From_Mouse_Vector_World_Rotation' has a wrong offset!");

// Function W_Command_ActionControl.W_Command_ActionControl_C.Get World Distance
// 0x0018 (0x0018 - 0x0000)
struct W_Command_ActionControl_C_Get_World_Distance final
{
public:
	float                                         World_Distance;                                    // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45BB[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelWidget*                           CallFunc_GetMapBody_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Get_World_Distance_from_Relative_Origin_World_Distance; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Command_ActionControl_C_Get_World_Distance) == 0x000008, "Wrong alignment on W_Command_ActionControl_C_Get_World_Distance");
static_assert(sizeof(W_Command_ActionControl_C_Get_World_Distance) == 0x000018, "Wrong size on W_Command_ActionControl_C_Get_World_Distance");
static_assert(offsetof(W_Command_ActionControl_C_Get_World_Distance, World_Distance) == 0x000000, "Member 'W_Command_ActionControl_C_Get_World_Distance::World_Distance' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_World_Distance, CallFunc_GetMapBody_ReturnValue) == 0x000008, "Member 'W_Command_ActionControl_C_Get_World_Distance::CallFunc_GetMapBody_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_World_Distance, CallFunc_Get_World_Distance_from_Relative_Origin_World_Distance) == 0x000010, "Member 'W_Command_ActionControl_C_Get_World_Distance::CallFunc_Get_World_Distance_from_Relative_Origin_World_Distance' has a wrong offset!");

// Function W_Command_ActionControl.W_Command_ActionControl_C.Get Pixel Distance
// 0x0018 (0x0018 - 0x0000)
struct W_Command_ActionControl_C_Get_Pixel_Distance final
{
public:
	float                                         Distance;                                          // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45BC[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelWidget*                           CallFunc_GetMapBody_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Get_Pixel_Distance_from_Relative_Origin_Pixel_Distance; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Command_ActionControl_C_Get_Pixel_Distance) == 0x000008, "Wrong alignment on W_Command_ActionControl_C_Get_Pixel_Distance");
static_assert(sizeof(W_Command_ActionControl_C_Get_Pixel_Distance) == 0x000018, "Wrong size on W_Command_ActionControl_C_Get_Pixel_Distance");
static_assert(offsetof(W_Command_ActionControl_C_Get_Pixel_Distance, Distance) == 0x000000, "Member 'W_Command_ActionControl_C_Get_Pixel_Distance::Distance' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Pixel_Distance, CallFunc_GetMapBody_ReturnValue) == 0x000008, "Member 'W_Command_ActionControl_C_Get_Pixel_Distance::CallFunc_GetMapBody_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Get_Pixel_Distance, CallFunc_Get_Pixel_Distance_from_Relative_Origin_Pixel_Distance) == 0x000010, "Member 'W_Command_ActionControl_C_Get_Pixel_Distance::CallFunc_Get_Pixel_Distance_from_Relative_Origin_Pixel_Distance' has a wrong offset!");

// Function W_Command_ActionControl.W_Command_ActionControl_C.Create Accept Deny
// 0x0030 (0x0030 - 0x0000)
struct W_Command_ActionControl_C_Create_Accept_Deny final
{
public:
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Grid_AcceptDeny_C*                   CallFunc_Create_ReturnValue;                       // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetMousePositionScaledByDPI_LocationX;    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetMousePositionScaledByDPI_LocationY;    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetMousePositionScaledByDPI_ReturnValue;  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45BD[0x3];                                     // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Command_ActionControl_C_Create_Accept_Deny) == 0x000008, "Wrong alignment on W_Command_ActionControl_C_Create_Accept_Deny");
static_assert(sizeof(W_Command_ActionControl_C_Create_Accept_Deny) == 0x000030, "Wrong size on W_Command_ActionControl_C_Create_Accept_Deny");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_GetOwningPlayer_ReturnValue) == 0x000000, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000008, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_Create_ReturnValue) == 0x000010, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_GetMousePositionScaledByDPI_LocationX) == 0x000018, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_GetMousePositionScaledByDPI_LocationX' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_GetMousePositionScaledByDPI_LocationY) == 0x00001C, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_GetMousePositionScaledByDPI_LocationY' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_GetMousePositionScaledByDPI_ReturnValue) == 0x000020, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_GetMousePositionScaledByDPI_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Command_ActionControl_C_Create_Accept_Deny, CallFunc_MakeVector2D_ReturnValue) == 0x000024, "Member 'W_Command_ActionControl_C_Create_Accept_Deny::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");

}

