#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CommandPrePlacement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "W_FloatingWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_CommandPrePlacement.W_CommandPrePlacement_C
// 0x0038 (0x02B0 - 0x0278)
class UW_CommandPrePlacement_C final : public UW_FloatingWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_W_CommandPrePlacement_C;            // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_0;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FVector                                Zero_Based_World_Location;                         // 0x0288(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45A3[0x4];                                     // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 SQAction;                                          // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             Created_Command_Control_Widget;                    // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void Created_Command_Control_Widget__DelegateSignature(class UW_Command_ActionControl_C* Widget);
	void ExecuteUbergraph_W_CommandPrePlacement(int32 EntryPoint);
	void Reset_Use();
	void On_Map_Mouse_Down(const struct FPointerEvent& Mouse_Event, const struct FVector& World_Location);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	void Set_Action(class UClass* Param_SQAction);
	void Get_Traced_Map_Location(struct FVector* Zero, struct FVector* Local);
	void Cache_Local_World_Location();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_CommandPrePlacement_C">();
	}
	static class UW_CommandPrePlacement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_CommandPrePlacement_C>();
	}
};
static_assert(alignof(UW_CommandPrePlacement_C) == 0x000008, "Wrong alignment on UW_CommandPrePlacement_C");
static_assert(sizeof(UW_CommandPrePlacement_C) == 0x0002B0, "Wrong size on UW_CommandPrePlacement_C");
static_assert(offsetof(UW_CommandPrePlacement_C, UberGraphFrame_W_CommandPrePlacement_C) == 0x000278, "Member 'UW_CommandPrePlacement_C::UberGraphFrame_W_CommandPrePlacement_C' has a wrong offset!");
static_assert(offsetof(UW_CommandPrePlacement_C, Image_0) == 0x000280, "Member 'UW_CommandPrePlacement_C::Image_0' has a wrong offset!");
static_assert(offsetof(UW_CommandPrePlacement_C, Zero_Based_World_Location) == 0x000288, "Member 'UW_CommandPrePlacement_C::Zero_Based_World_Location' has a wrong offset!");
static_assert(offsetof(UW_CommandPrePlacement_C, SQAction) == 0x000298, "Member 'UW_CommandPrePlacement_C::SQAction' has a wrong offset!");
static_assert(offsetof(UW_CommandPrePlacement_C, Created_Command_Control_Widget) == 0x0002A0, "Member 'UW_CommandPrePlacement_C::Created_Command_Control_Widget' has a wrong offset!");

}

