#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Legend_LayerInfo

#include "Basic.hpp"

#include "W_Legend_LayerInfo_classes.hpp"
#include "W_Legend_LayerInfo_parameters.hpp"


namespace SDK
{

// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.ExecuteUbergraph_W_Legend_LayerInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Legend_LayerInfo_C::ExecuteUbergraph_W_Legend_LayerInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "ExecuteUbergraph_W_Legend_LayerInfo");

	Params::W_Legend_LayerInfo_C_ExecuteUbergraph_W_Legend_LayerInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Legend_LayerInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.GetFOBExclusionRadius
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UW_Legend_LayerInfo_C::GetFOBExclusionRadius()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "GetFOBExclusionRadius");

	Params::W_Legend_LayerInfo_C_GetFOBExclusionRadius Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.Get_HorizontalBox_ToolTipWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Legend_LayerInfo_C::Get_HorizontalBox_ToolTipWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "Get_HorizontalBox_ToolTipWidget");

	Params::W_Legend_LayerInfo_C_Get_HorizontalBox_ToolTipWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.Get_FOBConstructionRadius_ToolTipWidget_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Legend_LayerInfo_C::Get_FOBConstructionRadius_ToolTipWidget_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "Get_FOBConstructionRadius_ToolTipWidget_0");

	Params::W_Legend_LayerInfo_C_Get_FOBConstructionRadius_ToolTipWidget_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.Get_HabProxyRadius_ToolTipWidget_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UW_Legend_LayerInfo_C::Get_HabProxyRadius_ToolTipWidget_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "Get_HabProxyRadius_ToolTipWidget_0");

	Params::W_Legend_LayerInfo_C_Get_HabProxyRadius_ToolTipWidget_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_Legend_LayerInfo.W_Legend_LayerInfo_C.GetFOBConstructionRadius
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UW_Legend_LayerInfo_C::GetFOBConstructionRadius()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Legend_LayerInfo_C", "GetFOBConstructionRadius");

	Params::W_Legend_LayerInfo_C_GetFOBConstructionRadius Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

