#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MapMarker_DirectorParent

#include "Basic.hpp"

#include "W_MapMarker_DirectorParent_classes.hpp"
#include "W_MapMarker_DirectorParent_parameters.hpp"


namespace SDK
{

// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.ExecuteUbergraph_W_MapMarker_DirectorParent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MapMarker_DirectorParent_C::ExecuteUbergraph_W_MapMarker_DirectorParent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "ExecuteUbergraph_W_MapMarker_DirectorParent");

	Params::W_MapMarker_DirectorParent_C_ExecuteUbergraph_W_MapMarker_DirectorParent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.OnRightClicked
// (Event, Protected, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::OnRightClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "OnRightClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Init Director Marker
// (BlueprintCallable, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Init_Director_Marker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Init Director Marker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Find Map Icon
// (BlueprintCallable, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Find_Map_Icon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Find Map Icon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MapMarker_DirectorParent_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Tick");

	Params::W_MapMarker_DirectorParent_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Update Size
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Update_Size()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Update Size");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MapMarker_DirectorParent.W_MapMarker_DirectorParent_C.Refresh Visibility
// (Public, BlueprintCallable, BlueprintEvent)

void UW_MapMarker_DirectorParent_C::Refresh_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MapMarker_DirectorParent_C", "Refresh Visibility");

	UObject::ProcessEvent(Func, nullptr);
}

}

